const std = @import("std");
pub const zio = @import("zio");

pub const request = @import("request/request.zig");
pub const response = @import("response/response.zig");
pub const router = @import("router/router.zig");
pub const app = @import("app/app.zig");
pub const context = @import("core/context.zig");
pub const server = @import("server/server.zig");
pub const path = @import("core/path.zig");
pub const websocket = @import("websocket/websocket.zig");
pub const http_exception = @import("core/http_exception.zig");
pub const app_error = @import("core/app_error.zig");
pub const error_handler = @import("core/error_handler.zig");
pub const cors_middleware = @import("middleware/cors.zig");
pub const serve_static = @import("middleware/serve_static.zig");
pub const session_middleware = @import("middleware/session.zig");
pub const logger_middleware = @import("middleware/logger.zig");
pub const request_id_middleware = @import("middleware/request_id.zig");
pub const db = @import("db/db.zig");
pub const mysql = @import("db/mysql.zig");

pub const Request = request.Request;
pub const Param = request.Param;
pub const Header = request.Header;
pub const FormError = request.FormError;
pub const ParseBodyError = request.ParseBodyError;
pub const ParseBodyOptions = request.ParseBodyOptions;
pub const ParsedBody = request.ParsedBody;
pub const ParsedBodyEntry = request.ParsedBodyEntry;
pub const ParsedBodyField = request.ParsedBodyField;
pub const DecodedQueryValues = request.DecodedQueryValues;
pub const ParsedHeaders = request.ParsedHeaders;
pub const ParsedHeaderEntry = request.ParsedHeaderEntry;
pub const ParsedHeaderField = request.ParsedHeaderField;
pub const ParsedFormData = request.ParsedFormData;
pub const ParsedFormFile = request.ParsedFormFile;
pub const ParsedFormFiles = request.ParsedFormFiles;
pub const ParsedFormFileEntry = request.ParsedFormFileEntry;
pub const ParsedFormFileField = request.ParsedFormFileField;
pub const Blob = request.Blob;
pub const ConnInfo = request.ConnInfo;
pub const RawRequest = request.RawRequest;
pub const BodyStream = request.BodyStream;
pub const BodyReader = request.BodyReader;
pub const BodyReadError = request.BodyReadError;
pub const BodyStreamError = request.BodyStreamError;
pub const SaveBodyError = request.SaveBodyError;
pub const SaveBodyOptions = request.SaveBodyOptions;
pub const SaveMultipartOptions = request.SaveMultipartOptions;
pub const SaveMultipartError = request.SaveMultipartError;
pub const SavedMultipart = request.SavedMultipart;
pub const SavedMultipartField = request.SavedMultipartField;
pub const SavedMultipartFile = request.SavedMultipartFile;

pub const Response = response.Response;
pub const Body = response.Body;
pub const StreamWriter = response.StreamWriter;
pub const StreamRuntime = response.StreamRuntime;
pub const SseWriter = response.SseWriter;
pub const SseEvent = response.SseEvent;
pub const SseRuntime = response.SseRuntime;
pub const StreamOptions = context.StreamOptions;
pub const App = app.App;
pub const Hono = app.App;
pub const Context = context.Context;
pub const HonoRequest = request.Request;
pub const Renderer = context.Renderer;
pub const ResponseOptions = context.ResponseOptions;
pub const ExecutionContext = context.ExecutionContext;
pub const WaitUntilTask = context.WaitUntilTask;
pub const Router = router.Router;
pub const RouterLimits = router.Limits;
pub const Route = router.Route;
pub const Handler = router.Handler;
pub const ErrorHandler = app.ErrorHandler;
pub const ContextHandler = app.ContextHandler;
pub const ContextMiddlewareHandler = app.ContextMiddlewareHandler;
pub const Server = server.Server;
pub const Options = server.Options;
pub const ZioRuntime = server.ZioRuntime;
pub const AppOptions = app.App.Options;
pub const AppRequestOptions = app.App.RequestOptions;
pub const GetPathFn = app.GetPathFn;
pub const WebSocketConnection = response.WebSocketConnection;
pub const WebSocketMessage = websocket.WebSocketMessage;
pub const WebSocketOwnedMessage = websocket.WebSocketOwnedMessage;
pub const WebSocketCloseInfo = websocket.WebSocketCloseInfo;
pub const WebSocketUpgradeOptions = websocket.WebSocketUpgradeOptions;
pub const HTTPException = http_exception.HTTPException;
pub const HTTPExceptionOptions = http_exception.HTTPException.Options;
pub const AppErrorDef = app_error.Def;
pub const AppErrorRegistry = app_error.Registry;
pub const AppErrorDetail = app_error.Detail;
pub const AppErrorDetailProvider = app_error.DetailProvider;
pub const ErrorHandlerOptions = error_handler.Options;
pub const CorsOptions = cors_middleware.Options;
pub const ServeStaticOptions = serve_static.Options;
pub const Session = session_middleware.Session;
pub const SessionManager = session_middleware.SessionManager;
pub const SessionOptions = session_middleware.Options;
pub const LoggerOptions = logger_middleware.Options;
pub const LoggerEntry = logger_middleware.Entry;
pub const RequestIdOptions = request_id_middleware.Options;

pub const CookieOptions = response.CookieOptions;
pub const DeleteCookieOptions = response.DeleteCookieOptions;
pub const CookieError = response.CookieError;
pub const SameSite = response.SameSite;
pub const CookiePriority = response.CookiePriority;
pub const CookiePrefix = response.CookiePrefix;

pub const html = response.html;
pub const body = response.bodyBytes();
pub const json = response.json;
pub const text = response.text;
pub const notFound = response.notFound;
pub const redirect = response.redirect;
pub const options = response.options;
pub const methodNotAllowed = response.methodNotAllowed;
pub const internalError = response.internalError;
pub const typedJson = response.typedJson;
pub const parseJson = response.parseJson;
pub const methodFromName = request.methodFromName;
pub const streamResponse = response.stream;
pub const sseResponse = response.sse;
pub const streamText = context.streamText;
pub const streamSSE = context.streamSSE;
pub const generateCookie = response.generateCookie;
pub const generateDeleteCookie = response.generateDeleteCookie;
pub const cleanPath = path.cleanPath;
pub const upgradeWebSocket = websocket.upgradeWebSocket;
pub const isWebSocketUpgrade = websocket.isWebSocketUpgrade;
pub const webSocketHandler = websocket.webSocketHandler;
pub const parseCloseMessage = websocket.parseCloseMessage;
pub const errorHandler = error_handler.errorHandler;
pub const cors = cors_middleware.cors;
pub const serveStatic = serve_static.serveStatic;
pub const session = session_middleware.session;
pub const sessionWithManager = session_middleware.sessionWithManager;
pub const logger = logger_middleware.logger;
pub const requestId = request_id_middleware.requestId;
pub const sessionContextKey = session_middleware.context_key;
pub const sessionManagerContextKey = session_middleware.manager_context_key;
pub const requestIdContextKey = request_id_middleware.context_key;

test {
    _ = request;
    _ = response;
    _ = router;
    _ = app;
    _ = context;
    _ = server;
    _ = path;
    _ = websocket;
    _ = http_exception;
    _ = app_error;
    _ = error_handler;
    _ = cors_middleware;
    _ = serve_static;
    _ = session_middleware;
    _ = logger_middleware;
    _ = request_id_middleware;
    _ = db;
    _ = mysql;

    try std.testing.expect(@hasDecl(@This(), "App"));
    try std.testing.expect(@hasDecl(@This(), "Hono"));
    try std.testing.expect(@hasDecl(@This(), "Context"));
    try std.testing.expect(@hasDecl(@This(), "Request"));
    try std.testing.expect(@hasDecl(@This(), "HonoRequest"));
    try std.testing.expect(@hasDecl(@This(), "Response"));
    try std.testing.expect(@hasDecl(@This(), "Router"));
    try std.testing.expect(@hasDecl(@This(), "RouterLimits"));
    try std.testing.expect(@hasDecl(@This(), "Server"));
    try std.testing.expect(@hasDecl(@This(), "ZioRuntime"));
    try std.testing.expect(@hasDecl(@This(), "upgradeWebSocket"));
    try std.testing.expect(@hasDecl(@This(), "webSocketHandler"));
    try std.testing.expect(@hasDecl(@This(), "HTTPException"));
    try std.testing.expect(@hasDecl(@This(), "AppErrorDef"));
    try std.testing.expect(@hasDecl(@This(), "AppErrorRegistry"));
    try std.testing.expect(@hasDecl(@This(), "AppErrorDetail"));
    try std.testing.expect(@hasDecl(@This(), "AppErrorDetailProvider"));
    try std.testing.expect(@hasDecl(@This(), "errorHandler"));
    try std.testing.expect(@hasDecl(@This(), "cors"));
    try std.testing.expect(@hasDecl(@This(), "serveStatic"));
    try std.testing.expect(@hasDecl(@This(), "session"));
    try std.testing.expect(@hasDecl(@This(), "sessionWithManager"));
    try std.testing.expect(@hasDecl(@This(), "Session"));
    try std.testing.expect(@hasDecl(@This(), "SessionManager"));
    try std.testing.expect(@hasDecl(@This(), "logger"));
    try std.testing.expect(@hasDecl(@This(), "requestId"));
    try std.testing.expect(@hasDecl(@This(), "db"));
    try std.testing.expect(@hasDecl(@This(), "mysql"));
    try std.testing.expect(!@hasDecl(@This(), "MySqlPool"));
    try std.testing.expect(!@hasDecl(@This(), "MySqlStatement"));
    try std.testing.expect(!@hasDecl(@This(), "MySqlTransaction"));

    try std.testing.expect(!@hasDecl(@This(), "fetchRequest"));
    try std.testing.expect(!@hasDecl(@This(), "FetchRequest"));
    try std.testing.expect(!@hasDecl(@This(), "proxy"));
    try std.testing.expect(!@hasDecl(@This(), "testClient"));
    try std.testing.expect(!@hasDecl(@This(), "validator"));
    try std.testing.expect(!@hasDecl(@This(), "jwt"));
    try std.testing.expect(!@hasDecl(@This(), "showRoutes"));
    try std.testing.expect(!@hasDecl(@This(), "routeManifest"));
}
